import Head from 'next/head'
import { gql, request,GraphQLClient } from 'graphql-request'
import Link from 'next/link'
const SERVICE_URL = "https://api-eu-central-1.hygraph.com/v2/cl6qbe2b62quj01tba1q78ncb/master"

const g_cms= new GraphQLClient( SERVICE_URL)
const query = gql`
query MyQuery {
  pamphletsConnection {
    edges {
      node {
        creator {
          about
          name
          id
          photo {
            url
          }
        }
        createdAt
        slug
        title
        excerpt
        featuredImage {
          url
        }
        manuals {
          name
          slug
        }
        note {
          html
        }
      }
    }
  }
}
  `  

export const getStaticProps= async()=>{ 
const {pamphletsConnection} =await g_cms.request(query)

return{ 
  props:{
    pamphletsConnection
  },
  revalidate:40
}
  }
  export default function Home({pamphletsConnection}) {
 
  return (
<div className='container'> 
<div>
<Head>
<title>Create Next App</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/favicon.ico" />
</Head> 

</div> 
<h1 className='haffHeader'> Handmaids</h1>
<div className='coverDiv'>  
{pamphletsConnection.edges.map((one, index)=>( 
<div className='midDiv'key={one.id}>
<h2 className='haffTitle'>{one.node.title}</h2>

<img 
className='display'
src={one.node.featuredImage.url}/> 

<div dangerouslySetInnerHTML={{__html:one.node.note.html}} className='mainContent'>
  
</div> 

<div className='author'> 
 <img
   src={one.node.creator.photo.url}
/>
<p>{one.node.creator.name}</p>
</div>

</div>
)  
)}   
 
  <div className='sideCollections'>
 {pamphletsConnection.edges.map((one)=>( 
     <div key={one.id}>
<p>{one.node.manuals.name}</p> 
</div>
    ) 
    )}  

</div>

  </div>
<footer>
<div className='footerDiv' > 
    Copyright &copy; {new Date().getFullYear()} Ngenet Studio   
  
</div>
</footer>

    </div>
  )
}
